# Generated by Django 5.0.2 on 2024-03-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='imageDimensions',
        ),
        migrations.AddField(
            model_name='pin',
            name='Dimentions_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='Dimentions_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
